controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - knee_joint
        - ankle_joint
      state_publish_rate: 50
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        - effort
      gains:
        joint1: {p: 100.0, d: 0.1}
        knee_joint: {p: 100.0, d: 0.1}
        ankle_joint: {p: 100.0, d: 0.1}
