name: Test RViz2 Setup

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-rviz2-setup:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 repository and keys
        run: |
          sudo apt update && sudo apt install -y curl gnupg2 lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt update

      - name: Install dependencies and RViz2
        run: |
          sudo apt install ros-humble-rviz2 -y
          source /opt/ros/humble/setup.bash
          chmod +x setup.sh
          ./setup.sh
          echo "APT Repositories:"
          cat /etc/apt/sources.list.d/* || echo "No repositories found."
          echo "Installed Packages:"
          dpkg -l | grep rviz || (echo "Error: RViz2 not found in installed packages!" && exit 1)

      - name: Verify RViz2 installation
        run: |
          source /opt/ros/humble/setup.bash
          if ! command -v rviz2 &> /dev/null; then
            echo "Error: RViz2 binary not found!" && exit 1
          fi
          echo "RViz2 binary located at: $(command -v rviz2)"
          rviz2 --version || (echo "Error: RViz2 version command failed!" && exit 1)

      - name: Test RViz2 command
        run: |
          sudo apt install ros-humble-rviz2 -y
          source /opt/ros/humble/setup.bash
          rviz2
