name: Test Gazebo Setup

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-setup:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and Gazebo
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Verify Gazebo installation
        run: |
          if ! ign --version; then
            echo "Gazebo Fortress is not installed!" && exit 1
          fi
          echo "Gazebo Fortress is installed successfully with version $(ign --version)."
